### ISSUE TITLE
Char Range Breaks application when somehow connected to Expression Result

### ISSUE THREAD

**Issue by robinduerhager** [johannesvollmer/regex-nodes-js#1]
**Describe the bug**
Using any Char Range node leads to an error which breaks the application:
`cannot read property '0' of null`

**To Reproduce**
1. Start the regex editor
2. Create a `Char Range` node
3. Plug the `Char Range` node directly into `Expression Result` node
4. See Error in console

**Expected behavior**
Using the `Char Range` node should compile and return a new valid regex

**Screenshots**

*Char Range nodes error:*
![Errors](https://user-images.githubusercontent.com/18482238/56428134-9b47e800-62be-11e9-9d82-3a9d6a7a4007.png)

**Additional context**
I tested every node and some in combination with others:
 * Both `Char Range` nodes lead to an error (See Screenshot above)
* The `Any Repetition` node crashes the website (feels like an infinite loop because the website freezes and crashes)
* Mixing the `Any-, Exact-, Ranged-Repitition` nodes lead to an invalid regex error which crashes the app (the user maybe shouldn't have the option to connect those)

**Comment by johannesvollmer** [comment]
Thanks. Yes, there are countless bugs (ticking the first checkbox of the default node will freeze everything). I can try to have a look at that ob Tuesday.

Your last point however is a UI design Problem. I'm not yet sure about a solution about that. Maybe we should have different types of connections, or just an error message instead of the regex?

**Comment by robinduerhager** [comment]
Will you maintain this project or will this be deprecated during the development of the elm alternative?

I think doing both would be beneficial for the user experience: restricting the user so the connections of multiple repetition nodes is not possible and giving a temporary error which states what went wrong.

EDIT: when connecting the node, we could try to compile the current network or run some checks, e.g. check if there are already repitition nodes in the pipeline and if yes just undo the last action.

**Comment by johannesvollmer** [comment]
The elm project does have priority, for many bugs will be prevented just by using a statically checked language. Design choices however will yet have to be made, regarding those validity checks.

**Comment by johannesvollmer** [comment]
Update:

Considering the ongoing progress of [the elm rewrite](https://johannesvollmer.github.io/regex-nodes/), I will close this issue, although not all features have been ported yet. I am sure the rewrite currently has none of the bugs you listed, such as freezing or crashing when connecting two nodes. Invalid regular expressions however are still possible, as I first want to port all features before handling invalid expressions.
